// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/discovery.proto

package diss

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FallInLoveRequest_XSizeEnum int32

const (
	FallInLoveRequest_normal FallInLoveRequest_XSizeEnum = 0
	FallInLoveRequest_small  FallInLoveRequest_XSizeEnum = 1
	FallInLoveRequest_big    FallInLoveRequest_XSizeEnum = 2
)

var FallInLoveRequest_XSizeEnum_name = map[int32]string{
	0: "normal",
	1: "small",
	2: "big",
}

var FallInLoveRequest_XSizeEnum_value = map[string]int32{
	"normal": 0,
	"small":  1,
	"big":    2,
}

func (x FallInLoveRequest_XSizeEnum) String() string {
	return proto.EnumName(FallInLoveRequest_XSizeEnum_name, int32(x))
}

func (FallInLoveRequest_XSizeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{2, 0}
}

type FallInLoveResponseSayEnum int32

const (
	FallInLoveResponse_noResponse FallInLoveResponseSayEnum = 0
	FallInLoveResponse_yes        FallInLoveResponseSayEnum = 1
	FallInLoveResponse_no         FallInLoveResponseSayEnum = 2
)

var FallInLoveResponseSayEnum_name = map[int32]string{
	0: "noResponse",
	1: "yes",
	2: "no",
}

var FallInLoveResponseSayEnum_value = map[string]int32{
	"noResponse": 0,
	"yes":        1,
	"no":         2,
}

func (x FallInLoveResponseSayEnum) String() string {
	return proto.EnumName(FallInLoveResponseSayEnum_name, int32(x))
}

func (FallInLoveResponseSayEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{3, 0}
}

type HelloRequest struct {
	HelloWord            string            `protobuf:"bytes,1,opt,name=helloWord,proto3" json:"helloWord,omitempty"`
	Custom               map[string]string `protobuf:"bytes,2,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetHelloWord() string {
	if m != nil {
		return m.HelloWord
	}
	return ""
}

func (m *HelloRequest) GetCustom() map[string]string {
	if m != nil {
		return m.Custom
	}
	return nil
}

type HelloResponse struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	SvcName              string   `protobuf:"bytes,2,opt,name=svcName,proto3" json:"svcName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *HelloResponse) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

type FallInLoveRequest struct {
	MarrageWord          string                      `protobuf:"bytes,1,opt,name=marrageWord,proto3" json:"marrageWord,omitempty"`
	Ring                 bool                        `protobuf:"varint,2,opt,name=ring,proto3" json:"ring,omitempty"`
	RingWeight           int32                       `protobuf:"varint,3,opt,name=ringWeight,proto3" json:"ringWeight,omitempty"`
	XSize                FallInLoveRequest_XSizeEnum `protobuf:"varint,4,opt,name=XSize,proto3,enum=proto.FallInLoveRequest_XSizeEnum" json:"XSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FallInLoveRequest) Reset()         { *m = FallInLoveRequest{} }
func (m *FallInLoveRequest) String() string { return proto.CompactTextString(m) }
func (*FallInLoveRequest) ProtoMessage()    {}
func (*FallInLoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{2}
}

func (m *FallInLoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallInLoveRequest.Unmarshal(m, b)
}
func (m *FallInLoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallInLoveRequest.Marshal(b, m, deterministic)
}
func (m *FallInLoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallInLoveRequest.Merge(m, src)
}
func (m *FallInLoveRequest) XXX_Size() int {
	return xxx_messageInfo_FallInLoveRequest.Size(m)
}
func (m *FallInLoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FallInLoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FallInLoveRequest proto.InternalMessageInfo

func (m *FallInLoveRequest) GetMarrageWord() string {
	if m != nil {
		return m.MarrageWord
	}
	return ""
}

func (m *FallInLoveRequest) GetRing() bool {
	if m != nil {
		return m.Ring
	}
	return false
}

func (m *FallInLoveRequest) GetRingWeight() int32 {
	if m != nil {
		return m.RingWeight
	}
	return 0
}

func (m *FallInLoveRequest) GetXSize() FallInLoveRequest_XSizeEnum {
	if m != nil {
		return m.XSize
	}
	return FallInLoveRequest_normal
}

type FallInLoveResponse struct {
	MarrageWord          string                    `protobuf:"bytes,1,opt,name=marrageWord,proto3" json:"marrageWord,omitempty"`
	Say                  FallInLoveResponseSayEnum `protobuf:"varint,2,opt,name=say,proto3,enum=proto.FallInLoveResponseSayEnum" json:"say,omitempty"`
	IsHappy              bool                      `protobuf:"varint,3,opt,name=isHappy,proto3" json:"isHappy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FallInLoveResponse) Reset()         { *m = FallInLoveResponse{} }
func (m *FallInLoveResponse) String() string { return proto.CompactTextString(m) }
func (*FallInLoveResponse) ProtoMessage()    {}
func (*FallInLoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e691ab039b136f4d, []int{3}
}

func (m *FallInLoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FallInLoveResponse.Unmarshal(m, b)
}
func (m *FallInLoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FallInLoveResponse.Marshal(b, m, deterministic)
}
func (m *FallInLoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FallInLoveResponse.Merge(m, src)
}
func (m *FallInLoveResponse) XXX_Size() int {
	return xxx_messageInfo_FallInLoveResponse.Size(m)
}
func (m *FallInLoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FallInLoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FallInLoveResponse proto.InternalMessageInfo

func (m *FallInLoveResponse) GetMarrageWord() string {
	if m != nil {
		return m.MarrageWord
	}
	return ""
}

func (m *FallInLoveResponse) GetSay() FallInLoveResponseSayEnum {
	if m != nil {
		return m.Say
	}
	return FallInLoveResponse_noResponse
}

func (m *FallInLoveResponse) GetIsHappy() bool {
	if m != nil {
		return m.IsHappy
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.FallInLoveRequest_XSizeEnum", FallInLoveRequest_XSizeEnum_name, FallInLoveRequest_XSizeEnum_value)
	proto.RegisterEnum("proto.FallInLoveResponseSayEnum", FallInLoveResponseSayEnum_name, FallInLoveResponseSayEnum_value)
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.HelloRequest.CustomEntry")
	proto.RegisterType((*HelloResponse)(nil), "proto.HelloResponse")
	proto.RegisterType((*FallInLoveRequest)(nil), "proto.FallInLoveRequest")
	proto.RegisterType((*FallInLoveResponse)(nil), "proto.FallInLoveResponse")
}

func init() { proto.RegisterFile("proto/discovery.proto", fileDescriptor_e691ab039b136f4d) }

var fileDescriptor_e691ab039b136f4d = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xae, 0x93, 0x66, 0xb7, 0x99, 0x85, 0x55, 0x18, 0x5a, 0x29, 0xac, 0x10, 0x84, 0x9c, 0x56,
	0x20, 0xa5, 0x52, 0x7a, 0xa0, 0x80, 0x38, 0xf0, 0xd3, 0xaa, 0x48, 0x88, 0x43, 0x7a, 0x28, 0xe2,
	0xe6, 0x6e, 0xac, 0xad, 0x85, 0x63, 0x2f, 0x76, 0x36, 0x52, 0x78, 0x08, 0x9e, 0x81, 0x57, 0xe0,
	0x4d, 0x78, 0x24, 0x14, 0xaf, 0xd3, 0x06, 0xd1, 0x15, 0x27, 0xcf, 0xf7, 0xe9, 0xf3, 0xe7, 0xf9,
	0xc6, 0x03, 0x07, 0x2b, 0xad, 0x6a, 0x75, 0x58, 0x72, 0xb3, 0x50, 0x0d, 0xd3, 0x6d, 0x66, 0x31,
	0x06, 0xf6, 0x48, 0x7f, 0x12, 0xb8, 0x73, 0xc6, 0x84, 0x50, 0x05, 0xfb, 0xb6, 0x66, 0xa6, 0xc6,
	0x87, 0x10, 0x5e, 0x75, 0xf8, 0x42, 0xe9, 0x32, 0x26, 0x09, 0x99, 0x87, 0xc5, 0x0d, 0x81, 0xcf,
	0x61, 0xb4, 0x58, 0x9b, 0x5a, 0x55, 0xb1, 0x97, 0xf8, 0xf3, 0x49, 0xfe, 0x78, 0xe3, 0x96, 0x0d,
	0x2d, 0xb2, 0x77, 0x56, 0x71, 0x22, 0x6b, 0xdd, 0x16, 0x4e, 0x3e, 0x7b, 0x01, 0x93, 0x01, 0x8d,
	0x11, 0xf8, 0x5f, 0x59, 0xeb, 0xfc, 0xbb, 0x12, 0xf7, 0x21, 0x68, 0xa8, 0x58, 0xb3, 0xd8, 0xb3,
	0xdc, 0x06, 0xbc, 0xf4, 0x8e, 0x49, 0xfa, 0x1a, 0xee, 0x3a, 0x7b, 0xb3, 0x52, 0xd2, 0x30, 0x44,
	0xd8, 0xa5, 0x65, 0xa9, 0xdd, 0x6d, 0x5b, 0x63, 0x0c, 0x63, 0xd3, 0x2c, 0x3e, 0xd1, 0xaa, 0x37,
	0xe8, 0x61, 0xfa, 0x9b, 0xc0, 0xbd, 0x53, 0x2a, 0xc4, 0x07, 0xf9, 0x51, 0x35, 0xac, 0x8f, 0x99,
	0xc0, 0xa4, 0xa2, 0x5a, 0xd3, 0x25, 0x1b, 0x04, 0x1d, 0x52, 0xdd, 0x2b, 0x9a, 0xcb, 0xa5, 0xb5,
	0xdb, 0x2b, 0x6c, 0x8d, 0x8f, 0x00, 0xba, 0xf3, 0x82, 0xf1, 0xe5, 0x55, 0x1d, 0xfb, 0x09, 0x99,
	0x07, 0xc5, 0x80, 0xc1, 0x63, 0x08, 0x3e, 0x9f, 0xf3, 0xef, 0x2c, 0xde, 0x4d, 0xc8, 0x7c, 0x9a,
	0xa7, 0x6e, 0x3a, 0xff, 0x3c, 0x9f, 0x59, 0xd5, 0x89, 0x5c, 0x57, 0xc5, 0xe6, 0x42, 0xfa, 0x0c,
	0xc2, 0x6b, 0x0e, 0x01, 0x46, 0x52, 0xe9, 0x8a, 0x8a, 0x68, 0x07, 0x43, 0x08, 0x4c, 0x45, 0x85,
	0x88, 0x08, 0x8e, 0xc1, 0xbf, 0xe4, 0xcb, 0xc8, 0x4b, 0x7f, 0x11, 0xc0, 0xa1, 0xa7, 0x9b, 0xcb,
	0xff, 0x33, 0x1d, 0x81, 0x6f, 0x68, 0x6b, 0x23, 0x4d, 0xf3, 0x27, 0xb7, 0x74, 0xb7, 0x71, 0xca,
	0x0c, 0x6d, 0x6d, 0x73, 0x9d, 0xba, 0x1b, 0x2d, 0x37, 0x67, 0x74, 0xb5, 0x6a, 0x6d, 0xe2, 0xbd,
	0xa2, 0x87, 0xe9, 0x53, 0x18, 0x3b, 0x25, 0x4e, 0x01, 0xe4, 0xf5, 0x0f, 0x45, 0x3b, 0x5d, 0xaf,
	0x2d, 0x33, 0x11, 0xc1, 0x11, 0x78, 0x52, 0x45, 0x5e, 0xfe, 0x83, 0xc0, 0xc1, 0x29, 0xd7, 0xa6,
	0x7e, 0xdf, 0x2f, 0xe2, 0x39, 0xd3, 0x0d, 0x5f, 0x30, 0xcc, 0x21, 0xb0, 0xff, 0x8b, 0xf7, 0x6f,
	0x59, 0xa6, 0xd9, 0xfe, 0xdf, 0xa4, 0x8b, 0xfa, 0x06, 0xe0, 0xa6, 0x6d, 0x8c, 0xb7, 0xcd, 0x79,
	0xf6, 0x60, 0x6b, 0xc6, 0xb7, 0xe1, 0x97, 0x71, 0x76, 0xf8, 0xaa, 0xe4, 0xc6, 0x5c, 0x8e, 0xac,
	0xe8, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x73, 0x7f, 0xa4, 0x2b, 0x03, 0x00, 0x00,
}
